# service : nginx for built version of the front app, based in dist/frontend/browser/ folder
# volumes: mount the dist/frontend/browser/ folder to /usr/share/nginx/html
# networks: connect to frontend network
services:
  nginx:
    image: nginx:1.27.3-alpine
    container_name: nginx

    volumes:
      - ./dist/frontend/browser:/usr/share/nginx/html
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=web

      - traefik.http.routers.front-matos.rule=Host(`matos.pierreleroyer.fr`)
      - traefik.http.routers.front-matos.entrypoints=websecure
      - traefik.http.routers.front-matos.tls=true
      - traefik.http.routers.front-matos.tls.certresolver=tlsresolver
      - traefik.http.routers.front-matos.priority=1

      - traefik.http.services.front-matos.loadbalancer.server.port=80

networks:
  web:
    external: true
